### PR TITLE
recuding the number of jobs in the CI, only running the last

### PR DESCRIPTION
**Pull request by bruAristimunha**

### CODE REVIEW

**Comment by tomMoral** [comment]
Not sure what is the purpose of this one

**Comment by bruAristimunha** [comment]
Hi, @tomMoral!

In a PR, each push executes continuous integration tests, however, within a PR, if you commit and push multiple times, like I do, you end up creating a queue of jobs and testing.

If you have tests that take 10 minutes longer, like here, this ends up generating a long queue to have one test done. This is kind of meaningless, as we always want to test only the last commit.

In this PR, we ensure that CI stop the tests for the previous push and runs the test only for the last one.

**Comment by tomMoral** [comment]
ah, this makes a lot of sense 😁 thanks ! could you do the same for benchopt and template_bemchmar?

**Comment by bruAristimunha** [comment]
done @tomMoral, In the https://github.com/benchopt/template_benchmark/pull/34 and https://github.com/benchopt/template_benchmark/pull/34 waiting for your approval.

**Pull request merged**
